### PR TITLE
Added some public access control and APNSCertificate public init

### PR DESCRIPTION
**Pull request by JacopoMangiavacchi**
There was access control compile error using this Package

### CODE REVIEW

**Comment by matteocrippa** [comment]
@JacopoMangiavacchi thx! 👍

**Comment by JacopoMangiavacchi** [comment]
Ciao Matteo ;-).  Any suggestion where to put the certificate files ?  I would like to create a Certificate folder in the Swift package that use Tori-APNS but I'm not sure about how to pass the file path.

Any suggestions ?  Tks

**Comment by matteocrippa** [comment]
hey @JacopoMangiavacchi I always used to set the absolute path of the files starting from the root / of the server.

Btw the most important thing is to force curl to install nghttp2 version in macOS, or it will not work at all

**Comment by JacopoMangiavacchi** [comment]
The problem with absolute path is supporting different type of deployment (bluemix, docker, macos etc.).  

Anyway I followed the instruction for forcing curl reinstal on macos but I always get this error:

checking for ZLIB... no
configure: error: Package requirements (zlib >= 1.2.3) were not met:
No package 'zlib' found

I tried to force reinstall zlib but got error too

Tks

**Comment by matteocrippa** [comment]
What's your macOS version? I'm running both 10.12 and 10.12.2 beta and it works fine for me

I've just tried to install on a new device in the office:

```
 ~  brew reinstall curl --with-openssl --with-nghttp2
==> Reinstalling curl with --with-nghttp2
==> Using the sandbox
==> Downloading https://curl.haxx.se/download/curl-7.50.3.tar.bz2
######################################################################## 100.0%
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/curl/7.50.3 --
==> make install
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/curl/lib
    CPPFLAGS: -I/usr/local/opt/curl/include
    PKG_CONFIG_PATH: /usr/local/opt/curl/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/curl/7.50.3: 367 files, 2.6M, built in 2 minutes 33 seconds
 ~  brew link curl --force
Linking /usr/local/Cellar/curl/7.50.3... 353 symlinks created
```

**Comment by matteocrippa** [comment]
hey @JacopoMangiavacchi did you manage to have this working? can I close this issue?

**Comment by JacopoMangiavacchi** [comment]
I got it work on linux but still openssl problem on macOS but you can definitely close the issue.  Thanks.

**Pull request merged**
